### ISSUE TITLE
Thoughts on debugging rejected promises

### ISSUE THREAD

**Issue by Ajaxy** [kriskowal/q#626] opened 2014-12-13 12:29 UTC
It's sad that with promises we're losing ability to pause execution on exceptions exactly where they were thrown.

We always have two absolutely different cases:
1) When something went wrong and regular exception was thrown. I.e. usual `ReferenceError` or `TypeError`. The same is when we are throwing our own exception, i.e. when we don't have enough arguments passed to some method.
2) When we want to say that current async operation has not finished successfully or even when it should not be executed at all. I.e. when we are about to do something that depends on user's permissions we'd like to have it that way:
```javascript
user.addFriend(friendId)
    .then(sendNotification, showFriendshipDisabledMessage)
    .then(showUserProfile)
```
To make this code work we have to throw an exception in `user.addFriend()` method to reject the operation promise. This is bad, because exception assumes something unexpected and critical. Here we have regular situation when some user has disabled friend requests and it's normal. We just have to notice current user about that and go on.

Now let's pretend we have that code synchronous. We'd hardly throw an exception in that place for client code to handle it by `try/catch`. We'd return `null` or `false` for him to just check it.
We could use that approach here, but then client code would be something like:
```javascript
user.addFriend(friendId).then(function (isFriendAdded) {
    if (isFriendAdded) {
        sendNotification().then(showUserProfile);
    } else {
        showFriendshipDisabledNotice();
    }

    return isFriendAdded;
})
```
That code looks awkward and promise chain is broken. Moreover we can realize here that we should name that method not `addFriend` but kind of `tryToAddFriend`.

Seems that finally it would be better to use previous approach and throw exception in `user.addFriend()`.
Now the worst thing is coming when we are about to debug that code. Either we use `done` or not we face strange behavior. If we do, we have exceptions when user has disabled friendship. If not, user will see that "friendship disabled" notice when we forget to pass `friendId` and real `TypeError` is thrown. 

Also regarding to #522 and #625 I assume that `done()` seems not to be obvious and natural. It's messing the logic and the debug. We always have to check the right spot to place it and remember to remove it, i.e. when we start to return promise. And it's out of spec, btw.

In our project we chose to adopt the convention that we don't reject promises by throwing exceptions but by returning another rejected promise (using analog of `Q.reject`). This allows us to setup the `debug mode` when exceptions in promises are not swallowed and we are able to pause execution on the right place and get full stack trace and navigate through it.

**Comment by leoselig** [comment] 2015-05-20 08:36
+1 for this
debugging exceptions (or rather detecting where they occured) is a pain atm

**Comment by kriskowal** [comment] 2015-05-20 15:47
You are not alone in these thoughts. Much of the conversation about promises involves these issues.

As for `.done()`, Q is a dialog with the Promise spec, not an adherent. Q influenced the evolution of the spec and the evolution of the spec influences Q. `.done()` may or may not become vestigial as developer tools improve.

Across the board, developer tools are exposing a promise inspector which shows unhandled rejections. The thing about an unhandled rejection that makes them unsuitable for plain old logging is that they can be eventually handled. Also, since a promise can be observed by anyone at any time, a handler can be introduced asynchronously. This is anticipated by the design.

Distinguishing operational errors from programmer errors is also a common topic. One could theoretically allow programmer errors to pass through and halt a program. This may or may not be desirable in production, mostly depending on whether a service is stateless, whether you manage your side-effects carefully, whether you can restart quickly, whether your availability matters more than your consistency, &c. So there is no one-size-fits-all for that. Using Q.reject to distinguish asynchronous operational errors from synchronous programmer errors is smart. Similarly, one could require Q.resolve for asynchronous resolution. At that point you have taken on all the burdens necessary to get rid of the recursive unwrapping feature of promises, then becomes equivalent to flatMap in the Monad world. But that’s a different library with a backward incompatible change to its semantics. I won’t even contemplate that for v2. That is not to say it is a bad idea.

The other issue is that promise chains branch and merge, as above. Ideally your whole program can be modeled as a single asynchronous function call with one way in and one way out, in which you would only ever call .done() once. That is admittedly difficult. Also, handling one branch of a promise chain does not necessarily mean that the root cause of an exception has also been handled by another branch of the promise chain. So, `a.then(b).done()` does not mean that `a.then(c).done()` should omit its `done()` clause, even though a rejected A promise would get reported twice.

In any case, I thank you for your thoughts. I am closing this issue for the purpose of triaging actionable issues. Continued discussion is welcome.

**Closed by kriskowal** 2015-05-20 15:47 UTC
