### ISSUE TITLE
Halt on promises-aplus-tests 2.x

### ISSUE THREAD

**Issue by hax** [kriskowal/q#666] opened 2015-03-18 17:10 UTC
Q currently use old promises-aplus-tests 1.x. If upgrade to latest promises-aplus-tests@2.1.0, it will halt on 2.3.1: If `promise` and `x` refer to the same object, reject `promise` with a `TypeError' as the reason.

**Comment by domenic** [comment] 2015-03-19 02:47
Dupe of #449

**Closed by domenic** 2015-03-19 02:47 UTC
